name: mrdqa_tool
description: Malaria Routine Data Quality Assessment Tool- A Checklist to Assess the Quality of Malaria Program Data

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  syncfusion_flutter_charts: ^18.3.38
  font_awesome_flutter: ^8.10.0
  flutter_markdown: ^0.4.4
  logger:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  markdown: ^2.1.8
  charts_common: ^0.12.0
  logging: ^1.0.2
  meta: ^1.7.0
  charts_flutter: ^0.12.0
  http: ^0.12.0+4
  flutter_form_builder: ^6.0.0
  select_form_field: ^2.0.0
  unicorndial: ^1.1.5
  flappy_search_bar: ^1.7.2
  async: ^2.4.2
  fluttertoast: ^7.1.6
  dropdown_formfield: ^0.1.4
  sqflite:
  path:
  grouped_buttons: ^1.0.4
  date_field: ^3.0.0
  multiselect_formfield: ^0.1.7
  csv: ^4.1.0
  uuid: 2.2.2
  flutter_email_sender: ^5.0.2
  encrypt: ^4.1.0
  path_provider: ^1.6.28
  permission_handler: ^5.1.0+2
  internet_connection_checker: ^0.0.1+3
  overlay_support: ^1.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/landing_page.png
    - assets/instructions.md
    - assets/indicator_page_title.md
    - assets/facility_info_page_title.md
    - assets/SECTIONS.csv
    - assets/PERIODS.csv
    - assets/SOURCE_DOCUMENT.csv
    - assets/DATA_ELEMENTS.csv
    - assets/ENTRY_DISCREPANCIES.csv
    - assets/cross_checks_help_text.md
    - assets/INDICATORS.csv
    - assets/supervision_form_help_text.md
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
